// <auto-generated />
namespace API_Lembretes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adiciona_Lembrete : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adiciona_Lembrete));
        
        string IMigrationMetadata.Id
        {
            get { return "202106260240495_Adiciona_Lembrete"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
